### ISSUE TITLE
vuepy.yml in component foder is not included

### ISSUE THREAD

**Issue by mahdi-b** [stefanhoelzl/vue.py#20]
Not sure if this is an intended or a missing feature, but given the followins structure:

```
- app.py
- index.html
- some_style.css
- vuepy.yml
- component_x
    - component_x.py
    - component_x.html
    - css
        - first.css
        - second.css  
    - vuepy.yml
```
testing `component_x` separately works fine but when including it in app.py, I need to explicitly copy the content of component_x/vuepy.yml into the main vuepy.yml to get it to work. I.e., in top-level vuepy.yml, I need to have the following:

```
templates:
  index: index.html
  componentx: component_x/component_x.html
stylesheets:
  - some_style.css
  - component_x/css/first.css
  - component_x/css/second.css
```

is there a way to avoid manually copying the content of component_x/yuepy.yml in the main vuepy.yml?

Thank you,
M
