### ISSUE TITLE
New update for Python 3.10

### ISSUE THREAD

**Issue by Kelvin-Data** [stefanhoelzl/vue.py#52]
I use the Python 3.10 version, does it support this version?

**Comment by stefanhoelzl** [comment]
vue.py uses [brython](https://github.com/brython-dev/brython) to run python in the browser.

You can try to add a `vuepy.yaml` and use a brython version supporting python 3.10
```yaml
scripts:
  brython: https://cdn.jsdelivr.net/npm/brython@3.13/brython.min.js
  brython-stdlib: https://cdn.jsdelivr.net/npm/brython@3.13/brython_stdlib.js
```
see also https://stefanhoelzl.github.io/vue.py/docs/management/configuration.html

I have not tested this and vue.py might be incompatible with another brython version.
